spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/game_card?useUnicode=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: 12345qwert
    hikari:
      minimum-idle: 10
      idle-timeout: 180000
      maximum-pool-size: 30
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
  data:
    redis:
      repositories:
        enabled: false
      host: 127.0.0.1
      port: 6379
      timeout: 600
      password: 123456
  task:
    execution:
      thread-name-prefix: 'task-'
    scheduling:
      pool:
        size: 3
      thread-name-prefix: 'scheduling-task-'
  security:
    filter:
      exclude:
        - /auth/signMessage
        - /admin/usd/assign
        - /admin/usd/balance
        - /admin/swap/ep
        - /node/list
        - /power/info
        - /token/price
        - /test/**

logging:
  pattern:
    console: '[%date] [%thread] [%logger{0}.%method] [%level] -> %msg%n'
    file: '[%date] [%thread] [%logger{0}.%method] [%level] -> %msg%n'
  level:
    root:
      info
    org.springframework.web: info
  file:
    name: 'logger/logger.log'

app:
#  chain_node_http_proxy: '127.0.0.1:1081' # Golang静态库Http网络代理 如果本地调试国内网路需要配置
  chain_node: 'https://data-seed-prebsc-1-s2.binance.org:8545' # BSC区块节点RPC端点 正式部署需要更换
  chain_id: 97 # BSC区块链ID  Mainnet: 56 Testnet: 97
  usdt : '0x3966aeb2c687ea5f64440ea494e6aa7690fac518' # BSC链中的USDT代币合约地址 全小写
  token_a: '0x2fb579556f7553aeb1148dc3badde1bfd2ca8d0e' # BSC链中的ART代币合约地址 全小写
  token_b: '0x6247d35e6562da66ace5fc7c0aa3e413c0dadcc5' # BSC链中的SOUL代币合约地址 全小写
  token_e_p: '0x24d3502d7d744479f4030ae7163643ae856ce324' # BSC链中的IOT代币合约地址 全小写
  release_contract: '0xd51fabdc3c646d180e2eefddadab5763ac678744' # BSC链中ART/SOUL释放合约地址 全小写
  community_address: '0x220c02643e25d5266c3ebf835e6ced86ad541fc6' #社区建设钱包
  technology_address: '0x907b0edf5785978f4dac4e811bd0d748ae0e3611' #技术钱包
  reng_gou_contract: '0x52eb217c47d7490f581385787fdd258d1d21ca16' # BSC链中节点人认购合约地址 全小写
  wallet_private_key: '3da496423db57730e5889ecd40ffa008b6b70438c5abbb2af481210e320eadf7' # 签到领取/批量转账钱包的私钥 全小写
  ep_ratio: 0.33 # EP兑换比例
  swap_public_key: '4f1ad087cd0868208767be52eb3946054918e77c30a94e07c33090e1fa732221'#兑换EP公钥